/* =========================================================
   FarmaClinic / ControlInventario - PostgreSQL schema
   Ejecutar en una base de datos PostgreSQL vacia o recreable.
   Este script borra y recrea las tablas.
========================================================= */

BEGIN;

/* =========================================================
   LIMPIEZA DE ESTRUCTURA
========================================================= */
DROP TABLE IF EXISTS movimiento_caja CASCADE;
DROP TABLE IF EXISTS saldo_caja_diario CASCADE;
DROP TABLE IF EXISTS movimiento_inventario CASCADE;
DROP TABLE IF EXISTS detalle_venta CASCADE;
DROP TABLE IF EXISTS venta CASCADE;
DROP TABLE IF EXISTS caja CASCADE;
DROP TABLE IF EXISTS producto CASCADE;
DROP TABLE IF EXISTS usuario CASCADE;

/* =========================================================
   TABLA USUARIO
========================================================= */
CREATE TABLE usuario (
    id_usuario INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    usuario VARCHAR(50) NOT NULL UNIQUE,
    password_hash VARCHAR(255) NOT NULL,
    nombre VARCHAR(100),
    rol VARCHAR(20) NOT NULL,
    activo BOOLEAN NOT NULL DEFAULT TRUE,
    fecha_creacion TIMESTAMP NOT NULL DEFAULT NOW(),
    CONSTRAINT ck_usuario_rol CHECK (rol IN ('Admin', 'Vendedor', 'Lector'))
);

/* =========================================================
   TABLA PRODUCTO
========================================================= */
CREATE TABLE producto (
    id_producto INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    codigo VARCHAR(50) NOT NULL UNIQUE,
    nombre VARCHAR(150) NOT NULL,
    descripcion VARCHAR(255),
    precio_ingreso NUMERIC(10,2) NOT NULL CHECK (precio_ingreso >= 0),
    precio_venta NUMERIC(10,2) NOT NULL CHECK (precio_venta >= 0),
    stock_actual INTEGER NOT NULL DEFAULT 0 CHECK (stock_actual >= 0),
    activo BOOLEAN NOT NULL DEFAULT TRUE,
    fecha_creacion TIMESTAMP NOT NULL DEFAULT NOW()
);

/* =========================================================
   TABLA CAJA
========================================================= */
CREATE TABLE caja (
    id_caja INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre VARCHAR(50) NOT NULL,
    saldo_actual NUMERIC(10,2) NOT NULL DEFAULT 0 CHECK (saldo_actual >= 0),
    activa BOOLEAN NOT NULL DEFAULT TRUE,
    fecha_creacion TIMESTAMP NOT NULL DEFAULT NOW()
);

/* =========================================================
   TABLA VENTA
========================================================= */
CREATE TABLE venta (
    id_venta INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    numero_venta INTEGER NOT NULL UNIQUE,
    fecha TIMESTAMP DEFAULT NOW(),
    id_usuario INTEGER NOT NULL,
    subtotal NUMERIC(10,2) NOT NULL CHECK (subtotal >= 0),
    total NUMERIC(10,2) NOT NULL CHECK (total >= 0),
    anulada BOOLEAN NOT NULL DEFAULT FALSE,
    activa BOOLEAN NOT NULL DEFAULT TRUE,
    CONSTRAINT fk_venta_usuario FOREIGN KEY (id_usuario)
        REFERENCES usuario(id_usuario)
);

/* =========================================================
   TABLA DETALLE DE VENTA
========================================================= */
CREATE TABLE detalle_venta (
    id_detalle_venta INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_venta INTEGER NOT NULL,
    id_producto INTEGER NOT NULL,
    cantidad INTEGER NOT NULL CHECK (cantidad > 0),
    precio_unitario NUMERIC(10,2) NOT NULL CHECK (precio_unitario >= 0),
    precio_ingreso NUMERIC(10,2) NOT NULL CHECK (precio_ingreso >= 0),
    subtotal NUMERIC(10,2) NOT NULL CHECK (subtotal >= 0),
    CONSTRAINT fk_detalle_venta_venta FOREIGN KEY (id_venta)
        REFERENCES venta(id_venta),
    CONSTRAINT fk_detalle_venta_producto FOREIGN KEY (id_producto)
        REFERENCES producto(id_producto)
);

/* =========================================================
   TABLA MOVIMIENTO DE INVENTARIO
========================================================= */
CREATE TABLE movimiento_inventario (
    id_movimiento INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_producto INTEGER NOT NULL,
    tipo_movimiento CHAR(1) NOT NULL CHECK (tipo_movimiento IN ('E', 'S')),
    cantidad INTEGER NOT NULL CHECK (cantidad > 0),
    fecha TIMESTAMP DEFAULT NOW(),
    referencia VARCHAR(50),
    id_referencia INTEGER,
    id_usuario INTEGER NOT NULL,
    CONSTRAINT fk_movinv_producto FOREIGN KEY (id_producto)
        REFERENCES producto(id_producto),
    CONSTRAINT fk_movinv_usuario FOREIGN KEY (id_usuario)
        REFERENCES usuario(id_usuario)
);

/* =========================================================
   TABLA SALDO DIARIO DE CAJA
========================================================= */
CREATE TABLE saldo_caja_diario (
    id_saldo_caja_diario INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_caja INTEGER NOT NULL,
    fecha DATE NOT NULL,
    saldo_inicial NUMERIC(10,2) NOT NULL DEFAULT 0,
    saldo_final NUMERIC(10,2) NOT NULL DEFAULT 0,
    total_ingresos NUMERIC(10,2) NOT NULL DEFAULT 0,
    total_egresos NUMERIC(10,2) NOT NULL DEFAULT 0,
    fecha_cierre TIMESTAMP NOT NULL DEFAULT NOW(),
    id_usuario_cierre INTEGER NOT NULL,
    cerrado BOOLEAN NOT NULL DEFAULT FALSE,
    CONSTRAINT fk_saldo_caja_caja FOREIGN KEY (id_caja)
        REFERENCES caja(id_caja),
    CONSTRAINT fk_saldo_caja_usuario FOREIGN KEY (id_usuario_cierre)
        REFERENCES usuario(id_usuario)
);

/* =========================================================
   TABLA MOVIMIENTO DE CAJA
========================================================= */
CREATE TABLE movimiento_caja (
    id_movimiento_caja INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_caja INTEGER NOT NULL,
    tipo_movimiento CHAR(1) NOT NULL CHECK (tipo_movimiento IN ('I', 'E')),
    monto NUMERIC(10,2) NOT NULL CHECK (monto > 0),
    fecha TIMESTAMP DEFAULT NOW(),
    concepto VARCHAR(50),
    id_referencia INTEGER,
    id_usuario INTEGER NOT NULL,
    saldo_en_momento NUMERIC(10,2) NOT NULL DEFAULT 0,
    CONSTRAINT fk_movcaja_caja FOREIGN KEY (id_caja)
        REFERENCES caja(id_caja),
    CONSTRAINT fk_movcaja_usuario FOREIGN KEY (id_usuario)
        REFERENCES usuario(id_usuario)
);

/* =========================================================
   INDICES
========================================================= */
CREATE INDEX ix_producto_codigo ON producto(codigo);
CREATE INDEX ix_venta_fecha ON venta(fecha);
CREATE INDEX ix_movinv_producto ON movimiento_inventario(id_producto);
CREATE INDEX ix_movcaja_fecha ON movimiento_caja(fecha);
CREATE INDEX ix_movcaja_saldo ON movimiento_caja(saldo_en_momento);
CREATE UNIQUE INDEX ux_saldo_caja_fecha_caja
    ON saldo_caja_diario(fecha, id_caja);

/* =========================================================
   DATA INICIAL
========================================================= */
INSERT INTO usuario (usuario, password_hash, nombre, rol, activo)
VALUES ('Kayala', 'Karina1', 'Karina Ayala', 'Admin', TRUE);

COMMIT;
